name = "archive-view-counter-db"
compatibility_date = "2026-07-20"
main = "src/index.ts"

[[d1_databases]]
binding = "archive_view_counter_db"
database_name = "archive-view-counter-db"
database_id = "46d0a9d3-7d3a-4069-9be6-d71fd17f4355"

